export { default as Add } from './Add'
export { default as BookDetail } from './BookDetail'
export { default as Home } from './Home'
export { default as Books } from './Books'
export { default as Profile } from './Profile'
export { default as Join } from './Join'
export { default as Login } from './Login'
